version: '3.8'
servives:
  db:
    image: postgres:16
    container_name: postgres-db
    enviroment:
      POSTGRES_USER: PostgresSQL 16
      POSTGRES_PASSWORD: 0910
      POSTGRES_DB: usuarios_db

      ports:
        -"5432:5432"

      volumes:
        -db-data:/var/lib/postgresql/data


    volumes:
      db-data:
